### ISSUE TITLE
Design intuitive menus and immersive cut-scenes.

### ISSUE THREAD

**Issue by SaiSVemula** [SaiSVemula/TowerAscent#11]
Ensure smooth scene transitions with loading screens if needed.
- Create accessible menus.
- Add well-designed cut-scenes.
- Implement smooth transitions with loading screens.

**Comment by mebs0** [comment]
menus have now been added

**Comment by SaiSVemula** [comment]
Hey, @mebs0 What do you think about this for the settings page

https://www.youtube.com/watch?v=-6H-uYh80vc&ab_channel=Tarodev
